CREATE SCHEMA IF NOT EXISTS cloud;
USE cloud;
CREATE TABLE IF NOT EXISTS usuarios(
	nome VARCHAR(60) NOT NULL,
	email VARCHAR(60) NOT NULL,
	senha VARCHAR(60) NOT NULL,
	id INT AUTO_INCREMENT,
	PRIMARY KEY (id)
);